# Generated by Django 4.0.4 on 2022-04-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_remove_book_genre_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Запас'),
        ),
    ]
