# Generated by Django 4.0.4 on 2022-04-19 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_book_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='existence',
        ),
        migrations.RemoveField(
            model_name='book',
            name='reader',
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='book',
            name='local_book',
            field=models.CharField(max_length=100, verbose_name='Геолокация'),
        ),
        migrations.CreateModel(
            name='RecordReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата взятия книги')),
                ('existence', models.BooleanField(null=True, verbose_name='На руках')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib.book', verbose_name='Автор')),
                ('reader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib.reader', verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
