# Generated by Django 4.0.4 on 2022-04-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0006_publisher_translator_remove_recordreader_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_limit',
            field=models.CharField(blank=True, choices=[('0+', '0+'), ('3+', '3+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], max_length=3, null=True, verbose_name='Возростное ограничение'),
        ),
    ]
