# Generated by Django 4.0.4 on 2022-04-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0007_alter_book_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='annotation',
            field=models.TextField(blank=True, null=True, verbose_name='Аннотация'),
        ),
    ]
