# Generated by Django 4.0.4 on 2022-04-27 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0008_alter_book_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, verbose_name='Имя')),
                ('lname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('city', models.CharField(max_length=40, verbose_name='Город')),
                ('index', models.CharField(max_length=40, unique=True, verbose_name='Почтовый индекс отделения')),
                ('check_post', models.BooleanField(default=False, verbose_name='Обработан')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
            },
        ),
    ]
