# Generated by Django 4.0.4 on 2022-04-27 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0009_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib.book', verbose_name='Книга'),
        ),
    ]
