# Generated by Django 4.0.4 on 2022-04-19 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='stock',
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Дата взятия книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='local_book',
            field=models.CharField(max_length=100, null=True, verbose_name='Геолокация'),
        ),
    ]
