# Generated by Django 4.0.4 on 2022-04-25 19:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0005_remove_book_date_remove_book_existence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('city', models.CharField(max_length=40, verbose_name='Город')),
                ('street', models.CharField(max_length=40, verbose_name='Улица')),
                ('home', models.PositiveIntegerField(verbose_name='Дом')),
                ('room', models.PositiveIntegerField(verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Переводчик',
                'verbose_name_plural': 'Переводчики',
            },
        ),
        migrations.RemoveField(
            model_name='recordreader',
            name='book',
        ),
        migrations.RemoveField(
            model_name='recordreader',
            name='reader',
        ),
        migrations.RemoveField(
            model_name='book',
            name='local_book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='stock',
        ),
        migrations.AddField(
            model_name='book',
            name='age_limit',
            field=models.PositiveIntegerField(blank=True, choices=[('0+', '0+'), ('3+', '3+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], null=True, verbose_name='Возростное ограничение'),
        ),
        migrations.AddField(
            model_name='book',
            name='annotation',
            field=models.TextField(blank=True, choices=[('0+', '0+'), ('3+', '3+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], verbose_name='Аннотация'),
        ),
        migrations.AddField(
            model_name='book',
            name='date_ls',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата издания'),
        ),
        migrations.AddField(
            model_name='book',
            name='numb_page',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество страниц'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='book',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
        migrations.DeleteModel(
            name='RecordReader',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib.publisher', verbose_name='Издательство'),
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib.translator', verbose_name='Переводчик'),
        ),
    ]
